CREATE TABLE "next-menu_customer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "next-menu_customer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerk_user_id" varchar(256) NOT NULL,
	"org_id" varchar(256) NOT NULL,
	"stripe_customer_id" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "next-menu_location" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "next-menu_location_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50),
	"slug" varchar(50),
	"org_id" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "next-menu_menu_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "next-menu_menu_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"location_id" integer NOT NULL,
	"name" varchar(256),
	"description" varchar(256),
	"price" numeric NOT NULL,
	"is_new" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "next-menu_menu_items_to_menus" (
	"menu_id" integer NOT NULL,
	"menu_item_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "next-menu_menu_items_to_menus_menu_id_menu_item_id_pk" PRIMARY KEY("menu_id","menu_item_id")
);
--> statement-breakpoint
CREATE TABLE "next-menu_menu" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "next-menu_menu_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"location_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "next-menu_location" ADD CONSTRAINT "next-menu_location_org_id_next-menu_customer_org_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."next-menu_customer"("org_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "next-menu_menu_item" ADD CONSTRAINT "next-menu_menu_item_location_id_next-menu_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."next-menu_location"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "next-menu_menu_items_to_menus" ADD CONSTRAINT "next-menu_menu_items_to_menus_menu_id_next-menu_menu_id_fk" FOREIGN KEY ("menu_id") REFERENCES "public"."next-menu_menu"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "next-menu_menu_items_to_menus" ADD CONSTRAINT "next-menu_menu_items_to_menus_menu_item_id_next-menu_menu_item_id_fk" FOREIGN KEY ("menu_item_id") REFERENCES "public"."next-menu_menu_item"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "next-menu_menu" ADD CONSTRAINT "next-menu_menu_location_id_next-menu_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."next-menu_location"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "location_name_idx" ON "next-menu_location" USING btree ("name");--> statement-breakpoint
CREATE INDEX "menu_item_name_idx" ON "next-menu_menu_item" USING btree ("name");--> statement-breakpoint
CREATE INDEX "menu_items_to_menus_menu_item_idx" ON "next-menu_menu_items_to_menus" USING btree ("menu_item_id");--> statement-breakpoint
CREATE INDEX "menu_items_to_menus_menu_idx" ON "next-menu_menu_items_to_menus" USING btree ("menu_id");--> statement-breakpoint
CREATE INDEX "menu_name_idx" ON "next-menu_menu" USING btree ("name");