CREATE TABLE "next-menu_organization" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "next-menu_organization_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerk_org_id" varchar(256) NOT NULL,
	"stripe_customer_id" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "next-menu_organization_clerk_org_id_unique" UNIQUE("clerk_org_id")
);
--> statement-breakpoint
CREATE TABLE "next-menu_user" (
	"id" integer NOT NULL,
	"role" varchar(10) NOT NULL,
	"clerk_user_id" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "next-menu_customer" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "next-menu_customer" CASCADE;--> statement-breakpoint
ALTER TABLE "next-menu_location" DROP CONSTRAINT "next-menu_location_org_id_next-menu_customer_org_id_fk";
--> statement-breakpoint
/* 
    Unfortunately in current drizzle-kit version we can't automatically get name for primary key.
    We are working on making it available!

    Meanwhile you can:
        1. Check pk name in your database, by running
            SELECT constraint_name FROM information_schema.table_constraints
            WHERE table_schema = 'public'
                AND table_name = 'next-menu_location'
                AND constraint_type = 'PRIMARY KEY';
        2. Uncomment code below and paste pk name manually
        
    Hope to release this update as soon as possible
*/

-- ALTER TABLE "next-menu_location" DROP CONSTRAINT "<constraint_name>";--> statement-breakpoint
ALTER TABLE "next-menu_location" ALTER COLUMN "id" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "next-menu_location" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "next-menu_location" ALTER COLUMN "slug" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "next-menu_user" ADD CONSTRAINT "next-menu_user_id_next-menu_organization_id_fk" FOREIGN KEY ("id") REFERENCES "public"."next-menu_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "next-menu_location" ADD CONSTRAINT "next-menu_location_id_next-menu_organization_id_fk" FOREIGN KEY ("id") REFERENCES "public"."next-menu_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "next-menu_location" DROP COLUMN "org_id";--> statement-breakpoint
ALTER TABLE "next-menu_location" ADD CONSTRAINT "next-menu_location_name_unique" UNIQUE("name");--> statement-breakpoint
ALTER TABLE "next-menu_location" ADD CONSTRAINT "next-menu_location_slug_unique" UNIQUE("slug");