ALTER TABLE "next-menu_location" DROP CONSTRAINT "next-menu_location_id_next-menu_organization_id_fk";
--> statement-breakpoint
ALTER TABLE "next-menu_user" DROP CONSTRAINT "next-menu_user_id_next-menu_organization_id_fk";
--> statement-breakpoint
ALTER TABLE "next-menu_location" ADD PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "next-menu_location" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "next-menu_location_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "next-menu_user" ADD PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "next-menu_user" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "next-menu_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "next-menu_location" ADD COLUMN "org_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "next-menu_user" ADD COLUMN "org_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "next-menu_location" ADD CONSTRAINT "next-menu_location_org_id_next-menu_organization_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."next-menu_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "next-menu_user" ADD CONSTRAINT "next-menu_user_org_id_next-menu_organization_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."next-menu_organization"("id") ON DELETE no action ON UPDATE no action;