CREATE TABLE "next-menu_order_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "next-menu_order_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"order_id" integer NOT NULL,
	"status" varchar(10) DEFAULT 'draft' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "next-menu_order" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "next-menu_order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"location_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "next-menu_order_item" ADD CONSTRAINT "next-menu_order_item_order_id_next-menu_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."next-menu_order"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "next-menu_order" ADD CONSTRAINT "next-menu_order_location_id_next-menu_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."next-menu_location"("id") ON DELETE no action ON UPDATE no action;